### ISSUE TITLE
how to config for next theme

### ISSUE THREAD

**Issue by laosijizhongcai** [bubkoo/hexo-filter-sequence#2]
i cannot display currently sequence use readme method

**Comment by bubkoo** [comment]
Could display currently with the default options?

**Comment by bubkoo** [comment]
@laosijizhongcai  Paste your config here.

**Comment by laosijizhongcai** [comment]
i use next theme,i add sequence in _config.yml,but cannot display sequence.
my default options is:
sequence:
  options: 
    theme: simple
    css_class:

**Comment by bubkoo** [comment]
@laosijizhongcai  reinstall it with v1.0.3

**Comment by laosijizhongcai** [comment]
npm install --save hexo-filter-sequence@1.0.3 ?

**Comment by bubkoo** [comment]
@laosijizhongcai correct

**Comment by laosijizhongcai** [comment]
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install" "--save" "hexo-filter-sequence@1.0.3"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! No compatible version found: hexo-filter-sequence@1.0.3
npm ERR! Valid install targets:
npm ERR! 1.0.2, 1.0.1, 1.0.0

**Comment by bubkoo** [comment]
@laosijizhongcai I forget to publish this version, and I have just publish it, pls try again.

**Comment by laosijizhongcai** [comment]
Generate: [sequence]webrtc-source-api-diagram-0.png
phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.


phantom stdout:   phantomjs://code/shim.js:1815 in send
  phantomjs://code/shim.js:1815 in _start
  phantomjs://code/shim.js:1842
