### ISSUE TITLE
只显示流程图

### ISSUE THREAD

**Issue by panzhenglian** [bubkoo/hexo-filter-sequence#5]
我装了你的另一个插件<https://github.com/bubkoo/hexo-filter-flowchart>,
如果写了流程图的情况下，当前页面会将下面的时序图加载出来，如果当前页面没有写流程图，就不加载了。

**Comment by bubkoo** [comment]
@panzhenglian 问题是就写了一个流程图，然后同时渲染了流程图和时序图对吗

**Comment by panzhenglian** [comment]
@bubkoo 你好，我当前页面如果没有写流程图，时序图就加载不出来。如果当前页面先写了流程图，再写时序图，就都可以加载出来。单独写流程图是可以的。
```
$ hexo version
hexo: 3.2.0
hexo-cli: 1.0.2
os: Darwin 16.6.0 darwin x64
http_parser: 2.7.0
node: 6.0.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2g
```

**Comment by chutian0610** [comment]
我也遇到了同样的问题，单独使用时序图时，html页面不显示，加上一个流程图，两个都可以显示。

* 查看两次生成的html文件，区别在于单独使用时序图时缺少下面这段代码
`<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"></script>`
* 我尝试
   * 在`renderer.js`文件里加上
`data.content += '<script src="' + config.raphael + '"></script>';`
   * 在`index.js`文件里加上
`raphael: 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js',`

然后运行`hexo clean`  `hexo s -g`，好像可以暂时解决问题。

**Comment by panzhenglian** [comment]
是的，加上这两行代码可以显示正常了，谢谢 @chutian0610
